### ISSUE TITLE
fixture/application#siblingAddon -> inRepoAddon

### ISSUE THREAD

**Issue by stefanpenner** [lennyburdette/ember-addon-broccoli-test-helper#8]
Its possible I am misunderstanding, but it seems that `siblingAddon` actually refers to `inRepoAddon` If so, that may be a more appropriate name.

**Comment by lennyburdette** [comment]
It

**Comment by lennyburdette** [comment]
I see what you're saying. This is using the same mechanism for addon discovery as in-repo addons, although it'll be used for full-fledged addons with their own dependencies. I'm not sure how important/useful that distinction is.
